version: 0.0
os: linux
hooks:
ApplicationStop:
    - location: assets/deploymentScripts/PrepareEnvironment.sh
  ApplicationStart:
    - location: assets/deploymentScripts/StartServices.sh
      timeout: 3600